"""empty message

Revision ID: f088ccdcec6d
Revises: ef88cb50ba97
Create Date: 2021-05-05 01:32:03.879502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f088ccdcec6d'
down_revision = 'ef88cb50ba97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
